# Generated by Django 4.0.5 on 2022-06-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DnaVerified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('dna', models.TextField(verbose_name='dna')),
                ('is_mutant', models.BooleanField(verbose_name='Is Mutant')),
            ],
            options={
                'verbose_name': 'Dna Verified',
                'verbose_name_plural': 'Dnas Verified',
                'db_table': 'adn_verified',
            },
        ),
    ]
